# ---------------------------------------------------------------------------
# Nursery — Terraform state-backend bootstrap
#
# Run this ONCE per AWS account (per region) before the main module's
# `terraform init`. Creates the S3 bucket that holds the main module's
# remote state, with versioning + encryption + public-access block, and
# writes `../backend.hcl` so the main module can be init'd against it.
#
# Bucket name is derived from your AWS account ID, so it's globally unique
# without needing user input.
#
# This module's own state stays local (gitignored). It manages exactly one
# bucket; teardown, if ever needed, is a manual `aws s3` operation —
# `prevent_destroy` blocks accidental Terraform destroys.
# ---------------------------------------------------------------------------

data "aws_caller_identity" "current" {}

locals {
  bucket_name = "nursery-tfstate-${data.aws_caller_identity.current.account_id}-${var.region}"

  common_tags = {
    ManagedBy = "nursery-terraform-bootstrap"
    Project   = "nursery"
    Purpose   = "terraform-state"
  }
}

resource "aws_s3_bucket" "tfstate" {
  bucket = local.bucket_name

  lifecycle {
    prevent_destroy = true
  }

  tags = local.common_tags
}

resource "aws_s3_bucket_versioning" "tfstate" {
  bucket = aws_s3_bucket.tfstate.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "tfstate" {
  bucket = aws_s3_bucket.tfstate.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "tfstate" {
  bucket = aws_s3_bucket.tfstate.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Materialize the main module's backend config as a partial-config file.
# `terraform init -backend-config=backend.hcl` in the main module picks
# this up automatically.
resource "local_file" "backend_hcl" {
  filename        = "${path.module}/../backend.hcl"
  file_permission = "0644"
  content = <<-EOT
    # Generated by hosts/aws/terraform/bootstrap. Do not edit by hand.
    bucket       = "${aws_s3_bucket.tfstate.bucket}"
    key          = "${var.state_key}"
    region       = "${var.region}"
    use_lockfile = true
    encrypt      = true
  EOT
}
