terraform {
  required_version = ">= 1.7"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.40"
    }
    http = {
      source  = "hashicorp/http"
      version = "~> 3.4"
    }
  }

  # Remote state in GCS (object versioning enabled; native consistent-read
  # locking — no external lock store needed). Bucket name is per-project,
  # so the actual config lives in backend.hcl — generated by `bootstrap/`
  # on first run, gitignored thereafter.
  #
  # Init flow (first time, per project):
  #   terraform -chdir=bootstrap init && terraform -chdir=bootstrap apply
  #   terraform init -backend-config=backend.hcl [-migrate-state]
  backend "gcs" {}
}

provider "google" {
  project = var.project_id
  region  = var.region
  zone    = var.zone
}
