terraform {
  # Pin to a recent stable Terraform. >=1.10 needed for S3 native locking
  # (use_lockfile in backend.hcl). 1.7 still works for local-state mode.
  required_version = ">= 1.10"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.60"
    }
    http = {
      source  = "hashicorp/http"
      version = "~> 3.4"
    }
  }

  # Remote state in S3 (native locking, no DynamoDB required).
  # Bucket name is per-account, so the actual config lives in backend.hcl
  # — generated by `bootstrap/` on first run, gitignored thereafter.
  # Init flow:
  #   terraform -chdir=bootstrap init && terraform -chdir=bootstrap apply
  #   terraform init -backend-config=backend.hcl [-migrate-state]
  backend "s3" {}
}

provider "aws" {
  region = var.region
}
