# ---------------------------------------------------------------------------
# Nursery — Terraform GCS state-backend bootstrap
#
# Run this ONCE per GCP project (per region) before the main module's
# `terraform init`. Creates the GCS bucket that holds the main module's
# remote state, with object versioning + uniform bucket-level access +
# enforced public access prevention, and writes `../backend.hcl` so the
# main module can be init'd against it.
#
# Bucket name is derived from your project ID + region, so it's globally
# unique without needing user input.
#
# Mirrors hosts/aws/terraform/bootstrap/ (S3 backend). Same shape, swapped
# provider. GCS handles state locking natively via consistent reads — no
# external lock store needed (the GCP equivalent of S3 native locking).
#
# This module's own state stays local (gitignored). It manages exactly one
# bucket with `prevent_destroy = true` to block accidental Terraform
# destroys of state itself.
# ---------------------------------------------------------------------------

locals {
  bucket_name = "nursery-tfstate-${var.project_id}-${var.region}"

  common_labels = {
    managed_by = "nursery-terraform-bootstrap"
    project    = "nursery"
    purpose    = "terraform-state"
  }
}

resource "google_storage_bucket" "tfstate" {
  name     = local.bucket_name
  location = var.region

  # Modern access control: IAM only, no per-object ACLs.
  uniform_bucket_level_access = true

  # Belt-and-suspenders: block any attempt to make the bucket public.
  public_access_prevention = "enforced"

  # Keep every prior version of the state file (Matthew's "old versions of
  # the cloud config" — yes, that's exactly what this does). No lifecycle
  # rule, so versions are retained indefinitely. State files are KB-sized,
  # so cost is negligible (fractions of a cent per month).
  versioning {
    enabled = true
  }

  lifecycle {
    prevent_destroy = true
  }

  labels = local.common_labels
}

# Materialize the main module's backend config as a partial-config file.
# `terraform init -backend-config=backend.hcl` in the main module picks
# this up automatically.
resource "local_file" "backend_hcl" {
  filename        = "${path.module}/../backend.hcl"
  file_permission = "0644"
  content = <<-EOT
    # Generated by hosts/gcp/terraform/bootstrap. Do not edit by hand.
    bucket = "${google_storage_bucket.tfstate.name}"
    prefix = "${var.state_prefix}"
  EOT
}
